spring:
  application.name: blog
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL}/${DATASOURCE_PATH}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  cloud:
    oci:
      storage:
        enabled: true
      config:
        region: ${ORACLE_REGION}
        fingerprint: ${ORACLE_FINGERPRINT}
        user-id: ${ORACLE_USER}
        tenant-id: ${ORACLE_TENANCY}
        private-key: ${ORACLE_KEY_PATH}
        type: simple
      region:
        static: ${ORACLE_REGION}
      compartment:
        static: ${ORACLE_COMPARTMENT}

server:
  shutdown: graceful


app:
  jwt:
    secret: ${JWT_SECRET:null}
    access_expires_after: 86400000
    refresh_expires_after: 172800000
    issuer: jombi
  bucket:
    bucket-type: ${STORAGE_TYPE:local}
    bucket-name: ${ORACLE_BUCKET_NAME}
